= A Bulk Price Cache for commercetools

This is a vert.x based HTTP service providing an commercetools API extension.

It is intended to keep large amounts of customer group (price list) and customer specific SKU prices in memory very efficiently.
I.e. it's designed for cases where commercetools is not the system of record for customer specific prices and the number of prices per SKU is high.

See BulkPricer.java for the HTTP API paths (To be documented here or in an OpenAPI spec)

The API extension serves cart creations and updates and overrides the cart price with an external price if it finds one for the given customer group or customer ID in its cache.
It does not complain if it does not find a more specific price, assuming the base price can be offered in any case.

It is based on the vert.x Gradle Starter and the ver.x Web REST example (forgot to purge the git history, still there). Originally a learning project.

== Prerequisites

* JDK 8+

== Running the project

Once you have retrieved the project, you can check that everything works with:

[source]
----
./gradlew test run
----

The command compiles the project and runs the tests, then  it launches the application.

== Anatomy of the project

The project contains:

* the Gradle project and its configuration (`build.gradle`)
* a _main_ verticle file (src/main/java/io/vertx/starter/MainVerticle.java), which starts the other Verticles
* a BulkPricer Verticle that represents the HTTP API and handles the direct responses
* a BulkPriceLoader Verticle that receives messages on the vert.x event bus to load a new price file for a specific price group from an external HTTP location in the background.


== Building the project

To build the project, just use:

----
./gradlew shadowJar
----

It generates a _fat-jar_ in the `build/libs` directory.


-----------
This project shows how to use the Vert.x 3.2 redeploy feature. Vert.x watches for file changes and will then compile these changes.
The verticles will be redeployed automatically.
Simply start the application with:

    ./gradlew run

Now point your browser at http://localhost:8080. Then you can make changes to the verticles and reload the browser.

